#!/bin/bash

# Only build if necessary
if [ -d "dlib/build" ]; then
    echo "DLib already built"
    exit 0
fi

# configure build process
cd dlib
mkdir build
cd build
cmake ..
if [ $? -ne 0 ]; then
    echo "Failed to configure DLib (CMake). Please check"
    exit 1
fi

# Actual build
make
if [ $? -ne 0 ]; then
    echo "Failed to build DLib as shared library (cmd make). Please check"
    exit 1
fi

# Check if file exists
if [ -f "libdlib.so" ]; then
    echo "DLib built as a shared library"
    exit 0
else
    echo "Could not find file libdlib.so, even though build was successful. Please check"
    exit 1
fi

